In [4]:
type(data)

dict

In [5]:
type(json_st1)

str

In [6]:
print(data)
print(json_st1)

{'name': 'ng van a', 'age': 23, 'skills': ['AI', 'python']}
{"name": "ng van a", "age": 23, "skills": ["AI", "python"]}


In [3]:
import json
data={"name":"ng van a","age":23,"skills":["AI","python"]}
json_st1=json.dumps(data,ensure_ascii=False)
print(json_st1)

{"name": "ng van a", "age": 23, "skills": ["AI", "python"]}


In [8]:
import json
data={"name":"ng van a","age":23,"skills":["AI","python"]}
json_st1=json.dumps(data,ensure_ascii=False)
print(json_st1)

{"name": "ng van a", "age": 23, "skills": ["AI", "python"]}


In [9]:
import json
def complex_handler(obj):
    if isinstance(obj,complex):
        return [obj.real,obj.imag]
    raise TypeError(repr(obj)+'khong the ma hoa Json')
data={"z":2+3j}
complex_obj=json.dumps(data,default=complex_handler)
print(complex_obj)

{"z": [2.0, 3.0]}


In [10]:
type(data)


dict

In [11]:
type(complex_obj)

str

In [12]:
data={"z":2+3j}
isinstance(data,complex)

False

In [13]:
type(data["z"])

complex

In [14]:
isinstance(data1,complex)

NameError: name 'data1' is not defined

In [15]:
json_st3=json.dumps({"z":1,"aI":2},sort_keys=True)
json_st3

'{"aI": 2, "z": 1}'

In [16]:
import json
data={
    "name":"a",
    "age":35,
    "company":"dat viet"
}
print(type(data))
json_string=json.dumps(data,ensure_ascii=False)
print(json_string)
print(type(json_string))

<class 'dict'>
{"name": "a", "age": 35, "company": "dat viet"}
<class 'str'>


In [17]:
import json
data ={
    "ho_va_ten": "Nguyễn Văn A", 
    "nam_sinh": 2025,
    "gioi_tinh": "Nam",
    "sdt": "0123456789",
    "email": "nguyenvana@uneti.edu.vn"
}
with open('thongtin.json','w',encoding='utf-8') as f:
    json.dump(data,f,ensure_ascii=False,indent=4)
print("du lieu da duoc ghi thanh cong vao tep'thongtin.json'.")


du lieu da duoc ghi thanh cong vao tep'thongtin.json'.


In [18]:
import json
def is_complex(object):
    if '__complex__' in object:
        return complex(object['real'],object['img'])
    return object
def main():
    complex_object=json.loads('{"__complex__":true,"real":4,"img":5}',
                              object_hook=is_complex)
    simplee_object=json.loads('{"real":6,"img":7}',
                              object_hook=is_complex)
    print("doi tuong so phuc....", complex_object)
    print("doi tuong binh thuong...", simplee_object)
if __name__=="__main__":
    main()


doi tuong so phuc.... (4+5j)
doi tuong binh thuong... {'real': 6, 'img': 7}


In [19]:
import json
with open('thongtin.json') as f:
    infor = json.load(f)
    print(infor)
    print(type(infor))

{'ho_va_ten': 'Nguyễn Văn A', 'nam_sinh': 2025, 'gioi_tinh': 'Nam', 'sdt': '0123456789', 'email': 'nguyenvana@uneti.edu.vn'}
<class 'dict'>


In [21]:
import json
class CustomObject:
    def __init__(self,data):
        self.data=data
    def to_dict(self):
        return{"custom_data":self.data}
class CustomObjectEncoder(json.JSONEncoder):
    def default(self,obj):
        if isinstance(obj,CustomObject):
            return obj.to_dict()
        return super().default(obj)
custom_obj=CustomObject({'key':'value'})
json_data=json.dumps(custom_obj,cls=CustomObjectEncoder)
print(json_data)

{"custom_data": {"key": "value"}}


In [22]:
import json
from json.decoder import JSONDecoder
colour_string='{"colour":["red","yellow"]}'
decoded_object=JSONDecoder().decode(colour_string)
print(decoded_object)
print(type(decoded_object))

{'colour': ['red', 'yellow']}
<class 'dict'>


In [23]:
!pip show requests

zsh:1: command not found: pip


In [24]:
!pip3 install requests


[notice] A new release of pip is available: 24.2 -> 25.2
[notice] To update, run: pip3 install --upgrade pip


In [25]:
!pip show requests

zsh:1: command not found: pip


In [28]:
import requests
# Thực hiện yêu cầu HTTP đến URL 'https://jsonplaceholder.typicode.com/posts'
response = requests.get('https://jsonplaceholder.typicode.com/posts')
# Kiểm tra xem yêu cầu thành công hay không
if response.status_code == 200:
# Nếu yêu cầu thành công, lấy dữ liệu JSON từ phản hồi json_data = response.json()
# In ra màn hình thông tin các bài đăng từ dữ liệu JSON
           for post in json_data:
               print("ID bài đăng:", post['id'])
               print("Tiêu đề:", post['title'])
               print("Nội dung:", post['body'])
               print("==================================")
else:
    print("Yêu cầu không thành công. Mã trạng thái:", response.status_code)

TypeError: string indices must be integers, not 'str'

In [1]:
!python –m pip install –upgrade pip 

zsh:1: command not found: python


In [2]:
!python –m pip install numpy

zsh:1: command not found: python


In [3]:
import numpy as np 
arr=np.array([1, 2, 3, 4])
print(arr)
print("NumPy version:", np.__version__)

[1 2 3 4]
NumPy version: 2.3.4


In [4]:
import numpy as np
np.__version__

'2.3.4'

In [5]:
import numpy as np
import sys
S=list(range(1000))
items_S=sys.getsizeof(S)
print("kích thước trong mỗi phần tử trong list:",items_S)
S_size=items_S*len(S)
print("kích thước của toàn bộ list:",S_size)
D=np.arange(1000)
print("kích thức mỗi phần tử của mảng Numpy:",D.itemsize)
array_size=D.itemsize*D.itemsize
print("kích thước của toàn bộ mảng Numpy:",array_size)
print(f"tỷ lệ (list/array):{S_size/array_size:.2f}")

kích thước trong mỗi phần tử trong list: 8056
kích thước của toàn bộ list: 8056000
kích thức mỗi phần tử của mảng Numpy: 8
kích thước của toàn bộ mảng Numpy: 64
tỷ lệ (list/array):125875.00


In [7]:
result = 0
print(type(result))
for i in range(100):
    result += i

<class 'int'>


In [8]:
result

4950

In [9]:
type(result)

int

In [10]:
import numpy as np
my_list=[1,2,3,4,5]
arr_2=np.array(my_list,dtype=float)
print(arr_2)

[1. 2. 3. 4. 5.]


In [11]:
import numpy as np
# Tạo mảng kích thước 5x5 các số thực có giá trị = 100
np.full((5,5),100,dtype=float)

array([[100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.]])

In [12]:
import numpy as np
 #Tạomảngchứa5giátrịtừ0đến10(gồmgiátrịkếtthúc) 3 
arr_1 = np.linspace(0, 10, 5)
print(arr_1)


[ 0.   2.5  5.   7.5 10. ]


In [13]:
arr_2 = np.linspace(0, 1, 10, endpoint=False)
print(arr_2)


[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [14]:
arr_3, step = np.linspace(1, 10, 100, retstep=True) 
print(arr_3)
print("Step size:", step)

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

In [15]:
import numpy as np
 # Tạo mảng gồm 5 phần tử từ 0 đến 10 với kiểu dữ liệu là float 
arr_4=np.linspace(0,10,num=5,dtype=float) 
print(arr_4)
print(arr_4.dtype)

[ 0.   2.5  5.   7.5 10. ]
float64


In [17]:
import numpy as np
2 #Tạomôtmảng1chiềugồm5giátrịngẫunhiêntừphânphốiđều 3 #trongkhoảngtừ0đến1
arr_5=np.random.random(5)
print(arr_5)


[0.82780733 0.85963143 0.99446174 0.78378169 0.72002233]


In [18]:
import numpy as np
2 # Tạo môt mảng 100 giá trị ngẫu nhiên từ phân phối chuẩn với # 3 trungbình0vàđộlệchchuẩnlà1.
arr_6=np.random.normal(loc=0.0,scale=1.0,size=100)
print(arr_6)

[ 1.58961408  0.02191676  1.64471701 -0.77718503 -0.53032356  0.1552646
  0.32058216 -1.25406317 -1.84446365 -0.15640004 -0.94718712  0.01476699
 -0.80250563 -0.51775464  0.80469982  0.62765915  0.09019257  1.10830682
 -0.36738662 -1.24053224  0.41168905  0.88177604  0.56793856  0.9572476
  0.96678094  0.56986069  1.2849685  -1.18162402 -0.58457798 -1.55938643
  0.316189    0.64121115 -0.41157079  0.70134143 -1.27016527 -1.20487918
  1.15211206  0.11769587 -0.28814208 -0.22911127  0.48071942  0.58058106
  1.25498793 -0.07813823 -0.25402159  0.10902103 -1.28369933  1.86073554
 -0.37760827  0.09159333 -1.99293899  1.49304684  1.13341698  0.95020116
 -0.97602834 -2.11516663  1.37955104  0.06926914  0.99869138  0.24654626
 -0.54368378  1.05400608 -0.94369528  1.14476447  0.00639549  0.21493324
  2.09676627 -0.70134577 -1.62572826  1.23471555  0.11979887  0.83471572
  0.02693052 -0.91230576 -0.45928821 -0.40456223  0.39442788  0.85748507
  0.83772738  1.23414162 -0.05726054 -0.39725698 -0.6

In [19]:
import numpy as np
2 #Tạomảngrỗnggồm5phầntử,giátrịcủa5phầntửnàycóthểlàbấtkỳgiátrị 3 # nào đã lưu trong bộ nhớ trước đó.
np.empty(5)

array([0.82780733, 0.85963143, 0.99446174, 0.78378169, 0.72002233])

In [23]:
import numpy as np 
arr=np.array([[1,2,3],[4,5,6]])
print("Số chiều của mảng là:",arr.ndim)
print("Kích thước của mảng là:",arr.shape)
print("Tổng số phần tử trong mảng là:", arr.size) 
print("Kiểu dữ liệu của các phần tử trong mảng là:", arr.dtype) 
print("Kích thước theo (byte) của mỗi phần tử trong mảng là:", arr.itemsize) 
print("Tổng kích thước theo (byte) của mảng là: ", arr.nbytes)

print("strides{bước nhảy bộ nhớ} la:",arr.strides)
print("tong chon trục o:",arr.sum(axis=0))
print("tong chon truc x:",arr.sum(axis=1))


Số chiều của mảng là: 2
Kích thước của mảng là: (2, 3)
Tổng số phần tử trong mảng là: 6
Kiểu dữ liệu của các phần tử trong mảng là: int64
Kích thước theo (byte) của mỗi phần tử trong mảng là: 8
Tổng kích thước theo (byte) của mảng là:  48
strides{bước nhảy bộ nhớ} la: (24, 8)
tong chon trục o: [5 7 9]
tong chon truc x: [ 6 15]


In [24]:
import numpy as np
arr_a=np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
np.sum(arr_a)

np.int64(78)

In [25]:
np.sum(arr_a,axis=0)

array([15, 18, 21, 24])

In [26]:
np.sum(arr_a,axis=1)

array([10, 26, 42])

In [27]:
import numpy as np

A=np.array([1, 2, 3, 4, 5])
A[0]

np.int64(1)

In [28]:
A[4]

np.int64(5)

In [29]:
import numpy as np
B=np.array([[1,2,3],[4,5,6],[7,8,9]])
B[1,2]

np.int64(6)